name: Auto Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Changelog Generator
        run: sudo gem install github_changelog_generator

      - name: Generate changelog
        run: github_changelog_generator -t ${{ secrets.GITHUB_TOKEN }} --base CHANGELOG.md --header-label "## Changelog" --unreleased false --output RELEASE_CHANGELOG.md

      - name: Read Changelog
        id: get_changelog
        run: echo "CHANGELOG=$(cat RELEASE_CHANGELOG.md)" >> $GITHUB_ENV

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ env.CHANGELOG }}
          draft: false
          prerelease: false
